# Generated by Django 3.1.2 on 2020-11-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='staged',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
