# Generated by Django 3.1.2 on 2020-11-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_voucher_staged'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.TextField()),
                ('payout', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
